### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by ruizhecao96** [IMLHF/PHASEN-PyTorch#1]
Hellow Could you please tell me if these results are based on the Voice Bank-Demand dataset?

**Comment by IMLHF** [comment]
> Hellow Could you please tell me if these results are based on the Voice Bank-Demand dataset?

yes，this results use the Voice Bank-Demand dataset same as that in paper

**Comment by IMLHF** [comment]
> Hellow Could you please tell me if these results are based on the Voice Bank-Demand dataset?

yes，this results are based on the Voice Bank-Demand dataset same as that in paper
