### ISSUE TITLE
Can you share your model?

### ISSUE THREAD

**Issue by yds1024** [IMLHF/PHASEN-PyTorch#3]
Do you have plans to open source the model?

**Comment by IMLHF** [comment]
which one

**Comment by BBBoobb** [comment]
> which one

all

**Comment by tianyajun123** [comment]
Running python -m PHASEN_009._2_train  Will report an error TypeError: forward() missing 1 required positional argument: 'L'，what would cause this？

**Comment by wp1120103773** [comment]
> Running python -m PHASEN_009._2_train Will report an error TypeError: forward() missing 1 required positional argument: 'L'，what would cause this？

i have the same problem.Have you solved it yet？

**Comment by wp1120103773** [comment]
modifing the line 92 ,let L = 48000, in the conv_stft.py can solve this problem.

**Comment by tianyajun123** [comment]
> modifing the line 92 ,let L = 48000, in the conv_stft.py can solve this problem.

ok,thank you very much！

**Comment by wp1120103773** [comment]
> 
You're welcome.Are you Chinese?If you like,I think that you can add me to qq：1120103773, so we can talk about some questions.

**Comment by wp1120103773** [comment]
Sorry，modifing the line 92 ,let L = 48000, in the conv_stft.py can‘t solve this problem，But i get the other way，let L=None，and  
 insert the line ：”L = outputs.size(-1)“ before line 111 “t = self.window.repeat(1,1,inputs.size(-1))**2”.I think this can solve the problem.

**Comment by IMLHF** [comment]
> Running python -m PHASEN_009._2_train Will report an error TypeError: forward() missing 1 required positional argument: 'L'，what would cause this？

fixed : https://github.com/IMLHF/PHASEN-PyTorch/blob/082444f505e662948d9702f4e844ebd37c453e7e/phasen_torch/models/phasen.py#L505

change line 504 in "phasen_torch/models/phasen.py" to "_mixed_wav_length = mixed_wav_batch.size()[-1]; est_clean_wav_batch = self._istft_fn(est_clean_stft_batch, _mixed_wav_length)".

The parameter "L" is similar with "length" in torch.istft. 
You could find this function at https://pytorch.org/docs/stable/generated/torch.istft.html?highlight=stft#torch.istft.
